### ISSUE TITLE
wrong input parameter parse

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [bhamon/gpuPlotGenerator#36]
./gpuPlotGenerator generate direct ./tmp/9633051684328757284_0_40_4096

Initializing generation contexts...
    [0] Path: ./tmp/9633051684328757284_0_4096_4096

**Comment by bhamon** [comment]
I don't see what is wrong with your output.
The `noncesNumber` must be a multiple of `staggerSize`. The plotter auto-corrected your mistake.

**Comment by vitaliy-kuzmich** [comment]
multiplied ? hmm, I expected that my result plot file would contain only 40 blocks.... 
docs says : For both strategies, the staggerSize parameter controls the temporary RAM buffer size.
so it is only tmp buffer size ?

**Comment by bhamon** [comment]
You can obtain 40 blocks, but you must specify a 40 `staggerSize` too :
```shell
./gpuPlotGenerator generate direct ./tmp/9633051684328757284_0_40_40
```

Originally the `staggerSize` controled the RAM buffer which was used to reorder the generated scoops (from all your working GPUs). Once full, the temp buffer was written to disc with a single write call (for the `buffer` strategy only).

Since I introduced a `direct` strategy, the whole reordering step is performed directly on the target disk. In this strategy the `staggerSize` has two direct impacts:
* It controls the amount of RAM dedicated to the partial reordering.
* The `4096*N` reordered scoops are then written to disk. The larger the `staggerSize` the larger the `N` factor thus improving the write calls efficiency.

**Comment by vitaliy-kuzmich** [comment]
thank you
